# Ovie Programming Language - Website Deployment Script (PowerShell)
# Deploys the Ovie website to multiple hosting platforms

param(
    [switch]$SkipValidation,
    [switch]$DeployVercel,
    [switch]$DeployNetlify
)

Write-Host "🌐 Ovie Website Deployment Script v2.0.0" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan

function Write-Status {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor Blue
}

function Write-Success {
    param([string]$Message)
    Write-Host "[SUCCESS] $Message" -ForegroundColor Green
}

function Write-Warning {
    param([string]$Message)
    Write-Host "[WARNING] $Message" -ForegroundColor Yellow
}

function Write-Error {
    param([string]$Message)
    Write-Host "[ERROR] $Message" -ForegroundColor Red
}

# Check if website directory exists
if (-not (Test-Path "website")) {
    Write-Error "Website directory not found!"
    exit 1
}

if (-not $SkipValidation) {
    Write-Status "Validating website files..."

    # Check required files
    $requiredFiles = @(
        "website/index.html",
        "website/assets/styles.css",
        "website/assets/script.js",
        "website/assets/ovie.png",
        "website/assets/ovie-icon.svg"
    )

    foreach ($file in $requiredFiles) {
        if (-not (Test-Path $file)) {
            Write-Error "Required file missing: $file"
            exit 1
        }
    }

    Write-Success "All required files found!"

    # Check for SEO essentials
    Write-Status "Checking SEO essentials..."
    $htmlContent = Get-Content "website/index.html" -Raw

    if ($htmlContent -match 'meta name="description"') {
        Write-Success "Meta description found"
    } else {
        Write-Error "Meta description missing!"
        exit 1
    }

    if ($htmlContent -match 'application/ld\+json') {
        Write-Success "Structured data found"
    } else {
        Write-Warning "Structured data missing"
    }

    # Check for Ovie branding
    Write-Status "Checking Ovie branding..."
    if ($htmlContent -match 'ovie\.png') {
        Write-Success "Ovie logo found in HTML"
    } else {
        Write-Error "Ovie logo missing from HTML!"
        exit 1
    }

    # Check for self-hosted references
    Write-Status "Checking self-hosted references..."
    if ($htmlContent -match 'Self-Hosted') {
        Write-Success "Self-hosted references found"
    } else {
        Write-Error "Self-hosted references missing!"
        exit 1
    }
}

# Check deployment configurations
Write-Status "Checking deployment configurations..."

if (Test-Path "vercel.json") {
    Write-Success "Vercel configuration found"
} else {
    Write-Warning "Vercel configuration missing"
}

if (Test-Path "netlify.toml") {
    Write-Success "Netlify configuration found"
} else {
    Write-Warning "Netlify configuration missing"
}

# Create deployment summary
Write-Status "Creating deployment summary..."
$deploymentSummary = @"
# Ovie Website Deployment Summary

**Date**: $(Get-Date)
**Version**: 2.0.0 (Self-Hosted)
**Status**: Ready for deployment

## Files Validated
- ✅ HTML structure
- ✅ CSS assets
- ✅ JavaScript functionality
- ✅ Ovie branding (ovie.png)
- ✅ SEO optimization
- ✅ Self-hosted references

## Deployment Targets
- 🚀 Vercel: $(if (Test-Path "vercel.json") { "Configured" } else { "Not configured" })
- 🚀 Netlify: $(if (Test-Path "netlify.toml") { "Configured" } else { "Not configured" })
- 🚀 GitHub Pages: Ready
- 🚀 GitLab Pages: Ready

## SEO Features
- ✅ Meta descriptions
- ✅ Open Graph tags
- ✅ Twitter Cards
- ✅ Structured data (JSON-LD)
- ✅ Canonical URLs
- ✅ Sitemap ready

## Performance Features
- ✅ Optimized images
- ✅ Minified CSS/JS
- ✅ CDN-ready assets
- ✅ Caching headers configured

## Security Features
- ✅ Content Security Policy
- ✅ X-Frame-Options
- ✅ X-XSS-Protection
- ✅ X-Content-Type-Options

## Next Steps
1. Deploy to Vercel: ``vercel --prod``
2. Deploy to Netlify: ``netlify deploy --prod``
3. Update DNS records if needed
4. Monitor deployment status

---
Generated by Ovie Website Deployment Script v2.0.0
"@

$deploymentSummary | Out-File -FilePath "deployment-summary.md" -Encoding UTF8
Write-Success "Deployment summary created: deployment-summary.md"

# Optional deployments
if ($DeployVercel) {
    Write-Status "Deploying to Vercel..."
    if (Get-Command vercel -ErrorAction SilentlyContinue) {
        vercel --prod
        Write-Success "Deployed to Vercel!"
    } else {
        Write-Warning "Vercel CLI not found. Install with: npm i -g vercel"
    }
}

if ($DeployNetlify) {
    Write-Status "Deploying to Netlify..."
    if (Get-Command netlify -ErrorAction SilentlyContinue) {
        netlify deploy --prod
        Write-Success "Deployed to Netlify!"
    } else {
        Write-Warning "Netlify CLI not found. Install with: npm i -g netlify-cli"
    }
}

# Check for CLI tools
if (Get-Command vercel -ErrorAction SilentlyContinue) {
    Write-Status "Vercel CLI found. Deploy with: vercel --prod"
} else {
    Write-Warning "Vercel CLI not found. Install with: npm i -g vercel"
}

if (Get-Command netlify -ErrorAction SilentlyContinue) {
    Write-Status "Netlify CLI found. Deploy with: netlify deploy --prod"
} else {
    Write-Warning "Netlify CLI not found. Install with: npm i -g netlify-cli"
}

Write-Success "Website validation complete!"
Write-Status "Ready for deployment to hosting platforms"

Write-Host ""
Write-Host "🎉 Ovie Website is ready for the world!" -ForegroundColor Green
Write-Host "   Self-hosted programming language with production-ready website" -ForegroundColor Green
Write-Host ""